# Generated by Django 3.2 on 2022-04-13 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projects_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='mark',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
