# Generated by Django 3.2 on 2022-04-13 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='frameworks/'),
        ),
    ]
