# Generated by Django 3.2 on 2022-04-19 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
        ('frameworks', '0002_alter_frameworks_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frameworks',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frameworks', to='languages.languages'),
        ),
    ]
