# Generated by Django 3.2 on 2022-04-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='purpose',
            field=models.CharField(choices=[('developer', 'developer'), ('qa', 'qa'), ('manager', 'manager')], default='developer', max_length=9),
        ),
    ]
