# Generated by Django 3.2 on 2022-04-07 08:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('projects', '0002_alter_projects_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QAEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_since', models.DateField(default=django.utils.timezone.now)),
                ('skill', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('english_level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='QA/')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Projects')),
                ('tasks', models.ManyToManyField(blank=True, default=None, to='tasks.Tasks')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'QA',
            },
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('work_since', models.DateField(default=django.utils.timezone.now)),
                ('skill', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('english_level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='B', max_length=1)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='managers/')),
                ('projects', models.ManyToManyField(blank=True, to='projects.Projects')),
                ('tasks', models.ManyToManyField(blank=True, default=None, to='tasks.Tasks')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Managers',
            },
        ),
    ]
