# Generated by Django 3.2 on 2022-04-07 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_alter_projects_mark'),
        ('frameworks', '0001_initial'),
        ('languages', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevToProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stats', models.BooleanField(default=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developers')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevToLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=3)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developers')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='languages.languages')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DevToFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveIntegerField(default=3)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developers.developers')),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frameworks.frameworks')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
