# Generated by Django 3.2 on 2022-04-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
        ('developers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='frameworks',
            field=models.ManyToManyField(to='frameworks.Frameworks'),
        ),
    ]
