# Generated by Django 3.2 on 2022-04-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frameworks', '0001_initial'),
        ('developers', '0002_alter_developers_frameworks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developers',
            name='frameworks',
            field=models.ManyToManyField(blank=True, default=None, to='frameworks.Frameworks'),
        ),
    ]
