name: Django CI

on:
  push:
    branches: [ main, developer, features ]
  pull_request:
    branches: [ main, developer ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint
        pip install pytest-cov
        pip install django-environ
        pip install djoser
    - name: Run Tests
      run: |
        pytest src/backend
    - name: Analysing the code with flake8
      run: |
        flake8
    - name: Check pytest coverage
      run: |
        pytest --cov src/backend
